# 测试环境
spring.profiles.active=test

# 应用名称
spring.application.name=demoApplication

# 服务端口，默认8080，如需修改改为8090等
server.port=8080

# ========== MySQL数据库连接配置 ==========
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# ========== MyBatis-Plus配置 ==========
mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
mybatis-plus.global-config.db-config.id-type=auto

# ========== Redis配置 ==========
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.password=
# 连接池配置（必须放在 lettuce.pool 下）
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=5
spring.data.redis.lettuce.pool.max-wait=2000ms

# 关闭SpringBoot启动Logo横幅
spring.main.banner-mode=off

# ========== JWT 配置 ==========
jwt.secret=YourSuperSecretKeyForJWTTokenGenerationMustBeAtLeast32CharactersLong
# 有效期 一天
jwt.expiration-ms=21600000
# 测试使用:10秒
#jwt.expiration-ms=10000

# ========== 逻辑删除 配置 =======
# MyBatis-Plus 逻辑删除配置（0，1状态一定要这样配置，否则会报错，MyBatis-Plus 默认约定）
mybatis-plus.global-config.db-config.logic-delete-field=is_deleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0